#############################################################################
#                                                                           #
#    https://towardsdatascience.com/diy-apache-spark-docker-bb4f11c10d24    #
#                                                                           #
#############################################################################

version: '3'

services:

  spark-master:
    image: holsi/spark_master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./build/libs:/opt/spark-apps
      - ./spark-data:/opt/spark-data
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: holsi/spark_worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./build/libs:/opt/spark-apps
      - ./spark-data:/opt/spark-data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker-2:
    image: holsi/spark_worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./build/libs:/opt/spark-apps
      - ./spark-data:/opt/spark-data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

#  spark-submit:
#    image: holsi/spark_submit
#    container_name: spark-submit
#    depends_on:
#      - spark-master
#    ports:
#      - "4040:4040"
#    environment:
#      - "SPARK_MASTER=spark://spark-master:7077"

